### ISSUE TITLE
Error stack traces are really bad

### ISSUE THREAD

**Issue by Kampfkarren** [jsdotlua/jest-lua#13]
Regularly, I'm not getting any interesting stack traces other than the erroring line itself. I need to print debug.traceback before I error usually to fix it.

**Comment by Kampfkarren** [comment]
Actually I think this might just be a me thing with how I'm using pcall.

**Comment by westurner** [comment]
- https://create.roblox.com/docs/reference/engine/globals/LuaGlobals#pcall
- https://create.roblox.com/docs/reference/engine/globals/LuaGlobals#xpcall :
  > Unlike pcall(), the err function preserves the stack trace of function f, which can be inspected using debug.info() or debug.traceback().
